export const GROUP_NODE_HEADER_HEIGHT = 48;
const GROUP_NODE_COLLAPSED_HEADER_MARGIN = 38;
const GROUP_NODE_COLLAPSED_BORDER_WIDTH = 2;

export const GROUP_NODE_COLLAPSED_HEIGHT =
    GROUP_NODE_HEADER_HEIGHT + GROUP_NODE_COLLAPSED_HEADER_MARGIN + 2 * GROUP_NODE_COLLAPSED_BORDER_WIDTH;
